# Generated by Django 5.1.1 on 2025-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, to='quizapp.question'),
        ),
    ]
