# Generated by Django 5.1.1 on 2025-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_userquiz_answered_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='quizapp.option'),
        ),
    ]
